<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.kk</groupId>
        <artifactId>kk-api</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>kk-admin-api</artifactId>
    <packaging>jar</packaging>
    <name>KK Admin API</name>
    <description>后台管理接口层</description>

    <dependencies>
        <dependency>
            <groupId>com.kk</groupId>
            <artifactId>kk-system</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kk</groupId>
            <artifactId>kk-biz</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>
</project>
