server:
  port: ${SERVER_PORT:8999}

spring:
  application:
    name: kk-manager
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 520MB
  data:
    redis:
      host: ${REDIS_HOST:host.docker.internal}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:pkFs2bXtZk9mh9Lxcye2}
      timeout: 3s
      repositories:
        enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://host.docker.internal:3306/kk_manager?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Lask5cy1pi8JQCAeFFbZ}
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      max-wait: 60000
      test-while-idle: true
      validation-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.kk.common.entity,com.kk.system.entity,com.kk.biz.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: Authorization
  timeout: 86400
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
  is-read-cookie: false
  is-read-header: true

kk:
  web:
    # 管理端前端域名（不要末尾斜杠），例如 https://admin.example.com
    base-url: ${KK_WEB_BASE_URL:https://154.44.25.190}
  file:
    storage:
      provider: rustfs
      prefix: kk-files
      ledger-voucher-prefix: ledger-vouchers
      max-size-mb: 500
      local:
        base-path: ${KK_FILE_LOCAL_PATH:./uploads}
      rustfs:
        endpoint: ${RUSTFS_ENDPOINT:http://host.docker.internal:9000}
        access-key: rustfsadmin
        secret-key: hjinrisYwDcPApsmb0WN
        bucket: ${RUSTFS_BUCKET:kk-manager}
        domain: ${RUSTFS_DOMAIN:http://154.44.25.190:9000}
  totp:
    issuer: KK Manager
    secret-master-key: ${TOTP_MASTER_KEY:KkTotp~SecretKey2026!ChangeMe}

logging:
  level:
    root: info
    com.kk: info

wallet:
  withdraw:
    tax-rate: ${WALLET_WITHDRAW_TAX_RATE:0.2}
